Update example with gosimports

diff --git a/example/do b/example/do
--- a/example/do
+++ b/example/do
@@ -56,6 +56,25 @@ build() {
 
 # This variable is used, but shellcheck can't tell.
 # shellcheck disable=SC2034
+help_run_goimports="Run goimports for package"
+run-goimports () {
+  command -v ./bin/gosimports > /dev/null || install-go-bin "github.com/rinchsan/gosimports/cmd/gosimports@v0.1.5"
+  ./bin/gosimports -local "github.com/circleci/your-service" -w "${@:-.}"
+}
+
+# This variable is used, but shellcheck can't tell.
+# shellcheck disable=SC2034
+help_lint="Run golanci-lint to lint go files."
+lint() {
+    ./bin/golangci-lint run "${@:-./...}"
+    if [ -n "$(./bin/gosimports -local "github.com/circleci/your-service" -d)" ]; then
+        echo "Go imports check failed, please run ./do run-goimports"
+        exit 1
+    fi
+}
+
+# This variable is used, but shellcheck can't tell.
+# shellcheck disable=SC2034
 help_lint="Run golanci-lint to lint go files."
 lint() {
     exec ./bin/golangci-lint run "${@:-./...}"
@@ -108,7 +127,8 @@ install-devtools() {
     curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ./bin v1.41.1
 
     install-go-bin \
-        "gotest.tools/gotestsum@v1.6.4"
+        "gotest.tools/gotestsum@v1.6.4" \
+        "github.com/rinchsan/gosimports/cmd/gosimports@v0.1.5"
 }
 
 install-go-bin() {
@@ -132,13 +152,6 @@ create-stub-test-files() {
         xargs -r --max-args=2 bash -c 'echo "package $0" > "$1/pkg_test.go"'
 }
 
-# This variable is used, but shellcheck can't tell.
-# shellcheck disable=SC2034
-help_run_goimports="Run goimports for package"
-run-goimports () {
-  command -v ./bin/goimports || install-go-bin "golang.org/x/tools/cmd/goimports@v0.0.0-20201208183658-cc330816fc52"
-  ./bin/goimports -local "github.com/circleci/your-service" -w "${@:-.}"
-}
 
 # This variable is used, but shellcheck can't tell.
 # shellcheck disable=SC2034
